services:
  postgres:
    image: postgres:15-alpine
    container_name: sales_etl_postgres
    environment:
      POSTGRES_DB: sales_dwh
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d sales_dwh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
